"""Pydantic v2 请求/响应模型。

约定：
- 所有响应统一包在 `ApiResponse[T]` 里（见 `common.py`），路由层用 `ApiResponse.ok(...)` 返回；
- 请求体模型命名 `XxxRequest`，响应体 `XxxOut` / `XxxDetail`，避免和 ORM 模型撞名。
"""

from app.schemas.common import CODE_OK, ApiResponse, HealthComponent, HealthReport, Page, PageMeta
from app.schemas.explore import (
    ExploreDoneOut,
    ExploreRequest,
    RecommendationOut,
    SchedulerOut,
    SubscribeRequest,
    SubscriptionOut,
)
from app.schemas.graph import (
    GraphAnalysisRequest,
    GraphAnalysisResult,
    GraphBuildRequest,
    GraphBuildResult,
    GraphEdge,
    GraphInsightRequest,
    GraphInsightResult,
    GraphNode,
    GraphOut,
)
from app.schemas.health import DbHealthReport, StoreHealth
from app.schemas.paper import (
    BatchUploadResult,
    ChunkOut,
    PaperCreate,
    PaperDetail,
    PaperOut,
    PaperUpdate,
    PaperUploadResult,
)
from app.schemas.qa import (
    AskRequest,
    AskResult,
    CitationOut,
    QAHistoryOut,
    RetrievalDebug,
    RetrievedChunkOut,
    SourceSpan,
    SourceTraceOut,
    TimelineItem,
    TraceRequest,
    TraceResult,
)
from app.schemas.tool import ToolCallRequest, ToolCallResult, ToolInfo, ToolListOut
from app.schemas.writing import (
    BilingualPair,
    CitationCheck,
    DiagramRequest,
    DiagramResult,
    ExpandRequest,
    ExpandResult,
    OutlineRequest,
    OutlineResult,
    OutlineSection,
    ReferenceOut,
    ReferenceRequest,
    ReferenceResult,
    TranslateRequest,
    TranslateResult,
    WriteRequest,
    WriteResult,
    WritingTemplateOut,
)

__all__ = [
    "CODE_OK",
    "ApiResponse",
    "AskRequest",
    "AskResult",
    "BatchUploadResult",
    "BilingualPair",
    "ChunkOut",
    "CitationCheck",
    "CitationOut",
    "DbHealthReport",
    "DiagramRequest",
    "DiagramResult",
    "ExploreDoneOut",
    "ExploreRequest",
    "ExpandRequest",
    "ExpandResult",
    "GraphAnalysisRequest",
    "GraphAnalysisResult",
    "GraphBuildRequest",
    "GraphBuildResult",
    "GraphEdge",
    "GraphInsightRequest",
    "GraphInsightResult",
    "GraphNode",
    "GraphOut",
    "HealthComponent",
    "HealthReport",
    "OutlineRequest",
    "OutlineResult",
    "OutlineSection",
    "Page",
    "PageMeta",
    "PaperCreate",
    "PaperDetail",
    "PaperOut",
    "PaperUpdate",
    "PaperUploadResult",
    "QAHistoryOut",
    "RecommendationOut",
    "ReferenceOut",
    "ReferenceRequest",
    "ReferenceResult",
    "RetrievalDebug",
    "RetrievedChunkOut",
    "SchedulerOut",
    "SourceSpan",
    "SourceTraceOut",
    "StoreHealth",
    "SubscribeRequest",
    "SubscriptionOut",
    "TimelineItem",
    "ToolCallRequest",
    "ToolCallResult",
    "ToolInfo",
    "ToolListOut",
    "TraceRequest",
    "TraceResult",
    "TranslateRequest",
    "TranslateResult",
    "WriteRequest",
    "WriteResult",
    "WritingTemplateOut",
]
